version: '3'
services:
    file-sync-app:
        image: file-sync:app
        networks:
            - my-network
        ports:
            - "80:80"
        depends_on:
            - file-sync-api
    file-sync-api:
        image: file-sync:api
        networks:
            - my-network
        ports:
            - "3001:3000"
networks:
    my-network:
        driver: bridge
