version: '3'
services:
    front:
        image: file-sync-front
        networks:
            - my-network
        ports:
            - "80:80"
        depends_on:
            - api
    api:
        image: file-sync-api
        networks:
            - my-network
        environment:
            - NODE_ENV=development
        ports:
            - "3000:3000"
networks:
    my-network:
        driver: bridge
