version: '3'
services:
    file-sync-app:
        image: alexv31/file-sync:app
        restart: always
        networks:
            - file-sync-network
        ports:
            - "3002:80"
            - "3003:443"
        depends_on:
            - file-sync-api
    file-sync-api:
        image: alexv31/file-sync:api
        restart: always
        environment:
            - NODE_ENV=
            - AUTHORIZED_ORIGIN=
            - FIREBASE_PROJECT_ID=
            - FIREBASE_PRIVATE_KEY=
            - FIREBASE_CLIENT_EMAIL=
            - FIREBASE_STORAGE_BUCKET=
            - ACCESS_TOKEN_SECRET=
        networks:
            - file-sync-network
        ports:
            - "4002:80"
            - "4003:443"
networks:
    file-sync-network:
        driver: bridge
