version: '3'
services:
    front:
        image: alexv31/file-sync:front
        networks:
            - my-network
        ports:
            - "80:80"
        depends_on:
            - api
    api:
        image: alexv31/file-sync:api
        networks:
            - my-network
        ports:
            - "3001:3000"
networks:
    my-network:
        driver: bridge
