version: '3'
services:
    file-sync-app:
        image: file-sync:app
        restart: always
        networks:
            - file-sync-network
        ports:
            - "3001:80"
            - "4001:443"
        depends_on:
            - file-sync-api
    file-sync-api:
        restart: always
        image: file-sync:api
        networks:
            - file-sync-network
        ports:
            - "5001:80"
            - "5002:443"
networks:
    file-sync-network:
        driver: bridge
