name: Docker build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: echo "test"
    - run: echo ${{ secrets.DOCKERHUB_USERNAME }}
    - run: docker build -t file-sync:app -f front/Dockerfile .
    - run: docker build -t file-sync:api -f api/Dockerfile .

  login-dockerhub:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

#  deploy-images:
#    needs: login-dockerhub
#    runs-on: ubuntu-latest
#    steps:
#     - name: Build and push
#       uses: docker/build-push-action@v5
#       with:
#         push: true
#         tags: user/app:latest
#    - uses: actions/checkout@v3
#    - run: docker tag file-sync:app ${{ secrets.DOCKERHUB_USERNAME }}/file-sync:app
#    - run: docker tag file-sync:api ${{ secrets.DOCKERHUB_USERNAME }}/file-sync:api
#    - run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/file-sync:app
#    - run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/file-sync:api