name: Docker build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: docker build -t file-sync:app -f front/Dockerfile .
    - run: docker build -t file-sync:api -f api/Dockerfile .

  deploy-image-docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to DockerHub
      run: echo ${{ secrets.DOCKERHUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - run: docker tag file-sync:app ${{ secrets.DOCKERHUB_USERNAME }}/file-sync:app
    - run: docker tag file-sync:api ${{ secrets.DOCKERHUB_USERNAME }}/file-sync:api
    - run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/file-sync:app
    - run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/file-sync:api