# This is a basic workflow to help you get started with Actions
# This workflow will build a docker image and push it to Docker Hub
# Setup environment variables in your repository settings (name of the environment : production)

name: Docker Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  APP_NAME: file-sync
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  PORTAINER_URL: ${{ secrets.PORTAINER_URL }}
  PORTAINER_ACCESS_TOKEN: ${{ secrets.PORTAINER_ACCESS_TOKEN }}
  PORTAINER_STACK_ID: ${{ secrets.PORTAINER_STACK_ID }}
  PORTAINER_ENDPOINT_ID: ${{ secrets.PORTAINER_ENDPOINT_ID }}

jobs:
  build-push-images:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      - name: Build images app and api
        run: |
          docker build -t  ${{ env.APP_NAME }}:app -f front/Dockerfile .
          docker build -t  ${{ env.APP_NAME }}:api -f api/Dockerfile .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.DOCKERHUB_USERNAME }}/${{ env.APP_NAME }}

      - name: Push image app
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: front/Dockerfile
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/${{ env.APP_NAME }}:app

      - name: Push image api
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: api/Dockerfile
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/${{ env.APP_NAME }}:api

  redeploy-stack-portainer:
    needs: build-push-images
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Re-deploy stack
        uses: wirgen/portainer-stack-redeploy-action@v1.1
        with:
          portainerUrl: ${{ env.PORTAINER_URL }}
          accessToken: ${{ env.PORTAINER_ACCESS_TOKEN }}
          stackId: ${{ env.PORTAINER_STACK_ID }}
          endpointId: ${{ env.PORTAINER_ENDPOINT_ID }}