name: Deploy to Firebase Hosting on merge
'on': push
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - run: npm ci
      - run: npm run build
        with:
          token: ${{ secrets.TOKEN }}